module.exports = {
	MARKET_KEY: {
		STATUS: "STATUS",
		TRANSACTION: "TRANSACTION",
		LATEST_WINNERS: "LATEST_WINNERS",
		RICHEST_PLAYERS: "RICHEST_PLAYERS",
	},
	GACHA_RATE_TYPE: {
		JACKPOT: "JACKPOT",
		ALL_IN_JACKPOT: "ALL_IN_JACKPOT",
		MYSTIC: "MYSTIC",
		SALT: "SALT"
	}
}