module.exports = {
	MARKET_KEY: {
		STATUS: "STATUS",
		TRANSACTION: "TRANSACTION"
	},
	GACHA_RATE_TYPE: {
		JACKPOT: "JACKPOT",
		ALL_IN_JACKPOT: "ALL_IN_JACKPOT",
		MYSTIC: "MYSTIC",
		SALT: "SALT"
	}
}